### ISSUE TITLE
DraggableView start closeToRight() / closeToLeft()

### ISSUE THREAD

**Issue by ameruddinjamil** [pedrovgs/DraggablePanel#88] opened 2016-02-23 05:02 UTC
Hello. 

I am using draggableView in my project. At the initializeDraggableView method, I already set the visibility to gone and closeToRight() which I hope when I first time click the list item, the draggableview will show an animation from right to top. But the draggableView just appear on top of the list item which is not so animated. But when I minimized the draggableView and close the draggableView by myself, and click at the other list item, the animation went well. 

Thank you.

**Comment by tuncaulubilge** [comment] 2016-05-05 14:42
Could you find any solutions to this issue? Tried several methods but no luck

**Comment by ameruddinjamil** [comment] 2016-05-05 14:54
Hi there,

Nope, still no solution.

**Comment by ppamorim** [comment] 2016-05-05 15:03
This is made by design, not a bug.

**Comment by tuncaulubilge** [comment] 2016-05-05 15:07
@ppamorim Any suggestions on how to change this? I can fork your project for this feature.

**Comment by ppamorim** [comment] 2016-05-05 15:14
You need to do some workarounds to pervent this problem. I solved this on my app doing this: 
- Start the view hidden 
- Call to move to close to right 
- Only show the view only the method to expand the view is called.

**Comment by tuncaulubilge** [comment] 2016-05-05 15:26
Found an ugly but working solution for this issue.

The trick is, the draggableView has to be visible when you call minimize(). In my layout, I made draggableView visible with both drag views invisible. 

When the draggableView global layout is called, I minimize the view and set it to invisible again in a delayed runnable. This way, when I want to display the views with maximize, the animation plays from bottom to top. 

Here is the code:

```
 playerView.getViewTreeObserver().addOnGlobalLayoutListener(
                new ViewTreeObserver.OnGlobalLayoutListener() {
                    @Override public void onGlobalLayout() {
                        // gets called after layout has been done but before display
                        playerView.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                        playerView.minimize();
                        Handler handler = new Handler();
                        handler.postDelayed(new Runnable() {
                            @Override public void run() {
                                playerView.setVisibility(View.INVISIBLE);
                                playerView.setChildViewsVisible();
                            }
                        }, 10);
                    }
                });
```

Afterwards, when I want to display the player, I just set it to VISIBLE and call maximize()

**Comment by pedrovgs** [comment] 2016-05-10 18:53
Sorry guys but this is the original behaviour of the library. As this is not a bug I'm closing the issue.

**Closed as completed by pedrovgs** 2016-05-10 18:53 UTC
