### ISSUE TITLE
DraggablePanel using ResizeTransformer goes below the screen and is half hidden.

### ISSUE THREAD

**Issue by Amritpal33** [pedrovgs/DraggablePanel#21] opened 2014-11-13 11:29 UTC
Hi,
   I am using Draggable panel and resizing feature to play videos. The issue is when i minimize the panel, it is half hidden in the screen and does not close to left or Right in minimize state.

Please Look into the issue.

**Comment by pedrovgs** [comment] 2014-11-13 11:30
Can you upload a video or screenshot with your problem?

**Comment by Fiddl3** [comment] 2014-11-13 11:39
It's because getMinHeightPlusMargin() in ResizeTransformer return different value than dimensions for   ~~verticalDragOffset ==1~~ verticalDragOffset ==0 in updateHeight()
I don't remember if there was another issue causing this....

ResizeTransformer from my form works OK but resizeFactor work different than in original library

**Comment by Amritpal33** [comment] 2014-11-13 12:04
How do i fix it..?
even the close to Left or right doesn't work for me.
I am testing on Nexus 5 and Samsung S4 with 4.4.2

**Comment by Fiddl3** [comment] 2014-11-13 12:12
I'm sure @pedrovgs will fix it very quick 

you can edit getMinHeightPlusMargin() to return the same value that is calculatet vile dragging

I think it will be:

``` java
return (int) ((getOriginalHeight()* (1/getYScaleFactor())) + getMarginBottom());
```

but I'm not sure

**Comment by pedrovgs** [comment] 2014-11-30 23:28
@Amritpal33 I'd like to review your problem, could be related to other changes not just with getMinHeightPlusMargin method. Can you upload one video or one screenshot reproducing your bug?

I'm working to fix one issue related to the horizontal drag effect, issue #20 . Can you review if this branch: https://github.com/pedrovgs/DraggablePanel/tree/fix-horizontal-drag-problems fix your problems?

**Comment by Amritpal33** [comment] 2014-12-04 08:00
Hi Pedrovgs,
     I took the latest update from Fiddl and it seemed to have solved maximum of my problems.
Also i will review the horizontal dragg effect branch.
 You might close this bug now.
Thanks for your efforts.

**Comment by pedrovgs** [comment] 2014-12-04 20:50
You might close this bug now? I need to integrate that fix and I'm waiting for a pull request of @Fiddl3 xD

**Comment by Fiddl3** [comment] 2014-12-04 20:53
I'll create new branch with fixes related to ResizeTransformer and send you a pull request.

**Comment by pedrovgs** [comment] 2014-12-04 20:57
Please, create different branches for different fixes. One to fix video view position using resize transformer, other to support landscape mode. Create your branches from the development tip.

To fix video view position you can change every variable related to video view position or size to int instead of use floats.

**Comment by Fiddl3** [comment] 2014-12-04 21:09
I think I already hanged all variables to int, except for scaleTransformer, but I will review this again...
This evening (very late) or tomorrow.  With fixes for landscape mode You will have to wait, when I find some time to figure out how really Scale transformer works (for ResizeTransformer it works and this is what I needed for my project). 
I'm working on project which requires rtmp stream (flv [x264+speex]) playback and I having some issues with audio/video sync... It's nightmare....

**Comment by pedrovgs** [comment] 2014-12-04 21:10
hahaha, good luck with your project! I'll wait for your PR. Thanks!

2014-12-04 22:09 GMT+01:00 Fiddl3 notifications@github.com:

**Comment by pedrovgs** [comment] 2014-12-05 00:14
@Fiddl3, @Amritpal33 I've found and fix the bug with VideoView and Resize transformer \o/. Thanks to some help of @Fiddl3 !!! Can you check if it's working fine to you and your applications? I'd like to release this fix to maven central this weekend. You have the code in this branch: https://github.com/pedrovgs/DraggablePanel/tree/fix-video-view-sample-problems

**Comment by Fiddl3** [comment] 2014-12-05 13:33
It'll not work...
int `getMinWidthPlusMarginRight()` "margin part is missing"

I'll update my for (ResizeTransformer_fix branch) with all fixes (without changing a scaleFactor implementation) then send you a pull request later today.

I still think that my scaleFactor implementation is better, but I don't know how many devs are using this library, and how many apps we "broke" when we will change this in maven central.... ergo lets leave this as is.

**Comment by pedrovgs** [comment] 2014-12-05 14:23
Ok @Fiddl3, I'll wait for your PR. But compile and check that branch. The sample project is working fine without take into account the right margin.

**Comment by Fiddl3** [comment] 2014-12-05 14:28
It's not working, look at the right side on the minimized dragView when you use `minimize()` method, there is no margin, so vertical dragging will not work.

**Comment by pedrovgs** [comment] 2014-12-05 14:44
This is a screenshot of video sample in a Nexus 5 -> https://drive.google.com/file/d/0B9xkpTnF9BXjZHh0Q2NBRi1TZkU/view?usp=sharing

And this in a Samsung Galaxy S3 -> https://drive.google.com/file/d/0B9xkpTnF9BXjOXZXQkRQM0F3X1U/view?usp=sharing

Vertical drag is also working :)

**Comment by Fiddl3** [comment] 2014-12-05 14:57
There is no way for this to work ok... look in to `smoothSlideTo()` left coordinate is calculated using `getMinWidthPlusMarginRight()` so it'll be moved right by margin size.

When you use finger to move view it'll work OK, but when you minimize it using `minimize()` or `smoothSlideTo()` it'll not

**Comment by pedrovgs** [comment] 2014-12-05 15:05
Here you have a video where the VideoView is released and `smoothSlideTo()` is executed as `minimize()` method does.

https://drive.google.com/file/d/0B9xkpTnF9BXjRzdQVU9fdEd5Z2s/view?usp=sharing

**Comment by pedrovgs** [comment] 2014-12-06 13:13
@Fiddl3 's pull request has been merged. I'm going to release a new version today :)

**Closed as completed by pedrovgs** 2014-12-06 13:13 UTC
Labels: bug
